---
title: "EEB274-exercise8"
author: "Kelly_Barr"
date: "March 1, 2017"
output: md_document
---

## Exploring Cocoli

rmarkdown::render("untitled2",output_format = "md_document")

```{r}
cocoli_dat<-read.table("/home/eeb177-student/Desktop/eeb274/class-assignments/class-assignments/21-Feb/cocoli.txt",header = TRUE)
head(cocoli_dat)
sizes_in_94 <- cocoli_dat$dbh1
names(sizes_in_94) <- cocoli_dat$tag
sizes_in_97 <- cocoli_dat$dbh2
sizes_in_98 <- cocoli_dat$dbh3
which(sizes_in_94 == 171)
```

```{r}
library(ggplot2)
ggplot(cocoli_dat) + geom_histogram(aes(dbh1)) + geom_histogram(aes(dbh2))+ ggtitle("distribution sizes '94") 

```

```{r}

housing <- read.csv("dataSets/landdata-states.csv")
head(housing[1:5])
hist(housing$Home.Value)

```
```{r}
ggplot(housing, aes(x = Home.Value)) +
  geom_histogram()
```
```{r}
plot(Home.Value ~ Date,
     data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="blue",
       data=subset(housing, State == "TX"))
legend(1975, 400000,
       c("MA", "TX"), title="State",
       col=c("black", "blue"),
       pch=c(1, 1))
```
```{r}
ggplot(subset(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point()
```
```{r}
hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = Land.Value)) +
  geom_point()
```
```{r}
hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ log(Land.Value), data = hp2001Q1))

p1 <- ggplot(hp2001Q1, aes(x = log(Land.Value), y = Structure.Cost))

p1 + geom_point(aes(color = Home.Value)) +
  geom_line(aes(y = pred.SC))
```
```{r}
p1 +
  geom_point(aes(color = Home.Value)) +
  geom_smooth()
```
```{r}
p1 + 
  geom_text(aes(label=State), size = 3)
```
```{r}

library("ggrepel")
p1 + 
  geom_point() + 
  geom_text_repel(aes(label=State), size = 3)
```
```{r}
p1 +
  geom_point(aes(size = 2),# incorrect! 2 is not a variable
             color="red") # this is fine -- all points red
```
```{r}
p1 +
  geom_point(aes(color=Home.Value, shape = region))
```
```{r}
dat <- read.csv("dataSets/EconomistData.csv")
head(dat)

ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point(color='blue')

```
```{r}
args(geom_histogram)
args(stat_bin)
p2 <- ggplot(housing, aes(x = Home.Value))
p2 + geom_histogram()


```
```{r}
p2 + geom_histogram(stat = "bin", binwidth=4000)
```
```{r}
housing.sum <- aggregate(housing["Home.Value"], housing["State"], FUN=mean)
rbind(head(housing.sum), tail(housing.sum))
```
```{r}
ggplot(housing.sum, aes(x=State, y=Home.Value)) + 
  geom_bar(stat="identity")
```
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(size = 2, color='blue') + geom_smooth(method = "lm")
```
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(size = 2, color='blue') + geom_line() + stat_smooth()
```
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(size = 2, color='blue') + geom_smooth(span = 1/3)
```
```{r}
p3 <- ggplot(housing,
             aes(x = State,
                 y = Home.Price.Index)) + 
        theme(legend.position="top",
              axis.text=element_text(size = 6))
(p4 <- p3 + geom_point(aes(color = Date),
                       alpha = 0.5,
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0)))

```
```{r}
p4 + scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"))
```
```{r}
p4 +
  scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"),
                         low = "blue", high = "red")
```
```{r}

p4 +
  scale_color_continuous(name="",breaks=c(1976,1994,2013),labels=c("'76","'94","'13"),low = "blue", high = "red")
```

```{r}
p4 +
  scale_color_gradient2(name="",
                        breaks = c(1976, 1994, 2013),
                        labels = c("'76", "'94", "'13"),
                        low = "blue",
                        high = "red",
                        mid = "gray60",
                        midpoint = 1994)
```
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(aes(color = dat$Region),
                       alpha = 0.5,
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0))
```
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(aes(color = Region), shape = 21, fill = "white",
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0)) + scale_color_manual(values = c("red","blue","orange","darkblue","yellow","orange4"),labels = c("Americas", "Asia Pacific", "Eastern Europe/Central Asia","Europian Union/Western Europe","Middle East/Northern Africa","Sub-Saharan Africa")) + labs(y = "Human Development Index", x = "Corruption Perception Index") + theme(legend.position = "top",legend.direction = "horizontal") + geom_text(aes(label = Country),check_overlap = TRUE)

```
```{r}
p5 <- ggplot(housing, aes(x = Date, y = Home.Value))
p5 + geom_line(aes(color = State))
```
```{r}
(p5 <- p5 + geom_line() +
   facet_wrap(~State, ncol = 10))
```
```{r}
p5 + theme_linedraw()
```
```{r}
p5 + theme_minimal() +
  theme(text = element_text(color = "turquoise"))
```
```{r}
theme_new <- theme_bw() +
  theme(plot.background = element_rect(size = 1, color = "blue", fill = "black"),
        text=element_text(size = 12, family = "Serif", color = "ivory"),
        axis.text.y = element_text(colour = "purple"),
        axis.text.x = element_text(colour = "red"),
        panel.background = element_rect(fill = "pink"),
        strip.background = element_rect(fill = "orange"))

p5 + theme_new
```

```{r}
country_col = c("Afghanistan", "Congo", "Sudan", "Myanmar", "Iraq", "India", "Venezuela", "Russia", "Argentina", "Greece", "Brazil", "Italy", "China", "South Africa", "Rwanda", "Bhutan", "Cape Verde", "Botswana", "Italy", "Spain", "France", "US", "Germany", "Britain", "Barbados", "Japan", "Norway", "Singapore", "New Zealand")



```

```{r}
plot_country <- rep(NA,173)
out_which <- which (dat$Country %in% country_col)
country_names <- as.character(dat$Country)
plot_country[out_which] <- country_names[out_which]
plot_country
```




```{r}
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(aes(color = Region), shape = 21, fill = "white",
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0)) + scale_color_manual(values = c("red","blue","orange","darkblue","yellow","orange4"),labels = c("Americas", "Asia Pacific", "Eastern Europe/Central Asia","Europian Union/Western Europe","Middle East/Northern Africa","Sub-Saharan Africa")) + labs(y = "Human Development Index", x = "Corruption Perception Index") + theme(legend.position = "top",legend.direction = "horizontal") + geom_smooth(se = FALSE, color = "red") +  geom_text_repel(dat = subset(dat,Country==plot_country), aes(label = Country), size = 3)

```
```{r}

```